### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by alexandre-mbm** [cadanimal/Hospitium#2]
- [ ] ~~`heroku` ‒ tentativa 1 - ver issue #1~~
  - [ ] `heroku-starter`  ‒ tentativa 1 - ver issue #11 
- [ ] `openshift` ‒ tentativa 2, caso a primeira falhe
- [x] `readme` ‒ melhoramento do `README.md` original - ver issue #3 
- [x] ~~`brazil` ‒ será o _branch_ principal, com `README.md` em pt-BR~~ - **não!** ver #4
- [ ] `pt-BR` ‒ será usado para fazer _pull requests_ de tradução testada - ver issue #5 

---

Outros branches no formato `PR-feature` serão usados para fazer pull  requests de cerejas escolhidas.
