### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alexandre-mbm** [cadanimal/Hospitium#6]
Transformar cada item numa _issue_ do projeto original

---
- [x] post to pet finder and other animal sites (adopt-a-pet)
- [x] click to call integration with twilio (be able to call vets, contacts, etc from computer with mic or bridge call)
- [x] create graphs of info and stats like average time in shelter etc
- [x] add current location to animal (like address of foster home or vet)
- [x] user docs (started at [https://hospitium.tenderapp.com/kb](https://hospitium.tenderapp.com/kb))
- [x] add more descriptions to labels in create and edit of all models
- [x] lots of testing
- [x] make adopt list random or cycle through entries
- [x] do public adopt pages grouped by organization - make embedable with code to copy in view
- [x] add search to adopt list (search by location and species)
- [x] add image to organization and contacts
- [x] mailchimp email list integration
- [x] create check for memcached server being up or available, if not, kick to db sessions
- [x] import animals from other sites in both batches and api style
- [x] add [aviary](http://www.aviary.com/) support to allow users to edit photos of animals
- [x] make public animal list a queue that is moderated by super admins (not yet - wait to see spam levels)
- [x] seo
- [x] send facebook to pages or groups
- [x] add label warning and make model strip any part of weight that isn't an integer (assumed grams)
- [x] remove and move to env variables all api keys
- [x] make weights decimals and make suffix user configurable 
- [x] graph of animal ages
- [x] do some cake thing on dashboard for animals birthdays
- [x] let organizations add donate links to public pages
- [x] mark what fields are public
- [x] donations and fundraising MVC 
- [x] maybe work with something like this [http://www.petdetect.com/](http://www.petdetect.com/)
- [x] create cancel account mechanism and job that deletes info in 30 days
- [x] track vet visits over time w/ notes
- [x] calculate most adopted species and do percentages of it
- [x] calculate average time from intake to adoption/death
- [x] switch notifications and use in all text area fields redcarpet
- [x] add note in add wordpress/adopt a pet accounts that they should create accounts for this, with unique usernames and strong passwords, with as little permissions as possible (not admin - just post ability)
- [x] Add better back button support for animal cards view. (return to the spot in the infinite scroll)
